// Code generated by ogen, DO NOT EDIT.
package oas

type ImagesGetRes interface {
	imagesGetRes()
}

type ImagesIDDeleteRes interface {
	imagesIDDeleteRes()
}

type ImagesIDGetRes interface {
	imagesIDGetRes()
}

type ImagesIDPutRes interface {
	imagesIDPutRes()
}

type ImagesPostRes interface {
	imagesPostRes()
}

type PingGetRes interface {
	pingGetRes()
}

type PostsGetRes interface {
	postsGetRes()
}

type PostsIDDeleteRes interface {
	postsIDDeleteRes()
}

type PostsIDGetRes interface {
	postsIDGetRes()
}

type PostsIDPutRes interface {
	postsIDPutRes()
}

type PostsPostRes interface {
	postsPostRes()
}
