// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ImagesGet implements GET /images operation.
//
// GET /images
func (UnimplementedHandler) ImagesGet(ctx context.Context) (r ImagesGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImagesIDDelete implements DELETE /images/{id} operation.
//
// DELETE /images/{id}
func (UnimplementedHandler) ImagesIDDelete(ctx context.Context, params ImagesIDDeleteParams) (r ImagesIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImagesIDGet implements GET /images/{id} operation.
//
// GET /images/{id}
func (UnimplementedHandler) ImagesIDGet(ctx context.Context, params ImagesIDGetParams) (r ImagesIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImagesIDPut implements PUT /images/{id} operation.
//
// PUT /images/{id}
func (UnimplementedHandler) ImagesIDPut(ctx context.Context, req *CreateImage, params ImagesIDPutParams) (r ImagesIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImagesPost implements POST /images operation.
//
// POST /images
func (UnimplementedHandler) ImagesPost(ctx context.Context, req *CreateImage) (r ImagesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PingGet implements GET /ping operation.
//
// GET /ping
func (UnimplementedHandler) PingGet(ctx context.Context) (r PingGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsGet implements GET /posts operation.
//
// GET /posts
func (UnimplementedHandler) PostsGet(ctx context.Context) (r PostsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsIDDelete implements DELETE /posts/{id} operation.
//
// DELETE /posts/{id}
func (UnimplementedHandler) PostsIDDelete(ctx context.Context, params PostsIDDeleteParams) (r PostsIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsIDGet implements GET /posts/{id} operation.
//
// GET /posts/{id}
func (UnimplementedHandler) PostsIDGet(ctx context.Context, params PostsIDGetParams) (r PostsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsIDPut implements PUT /posts/{id} operation.
//
// PUT /posts/{id}
func (UnimplementedHandler) PostsIDPut(ctx context.Context, req *CreatePost, params PostsIDPutParams) (r PostsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsPost implements POST /posts operation.
//
// POST /posts
func (UnimplementedHandler) PostsPost(ctx context.Context, req *CreatePost) (r PostsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
